language: scala
scala:
  - 2.12.10
  - 2.13.1
jdk:
  - openjdk8
script:
  - sbt -Dsbt.color=always -Dsbt.supershell=false ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
  - sbt -Dsbt.color=always -Dsbt.supershell=false ++$TRAVIS_SCALA_VERSION coverageReport coverageAggregate coveralls
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
