language: scala
scala:
  - 2.11.12
  - 2.12.7
jdk:
  - oraclejdk8
script:
  - sbt -S-Xfatal-warnings ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coverageAggregate coveralls
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
